spring:
  datasource:
    url: jdbc:sqlserver://ANISHNEWPC;database=appointmentdb;Integrated Security=False;encrypt=true;trustServerCertificate=true;
    username: sa
    password: sa@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 8085